### PR TITLE
addresses json

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[README.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1#-Mt7lqy73GuRmW_pWIm1:-Mt7lqy87khePMg4u3iK:bprk8vb) ([raw file](https://github.com/starkware-libs/starknet-addresses/blob/47704229c871eadbcc886ce4091dbf81df9dcad2/README.md#L17)):*
> ```Markdown
>     * Mainnet: [0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60](https://etherscan.io/address/0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60)
> 
> ## Bridged Tokens
> ```

add something that mentions that it's per network, and that it is in the format of a json.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

___
*[README.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1#-Mt7lqy73GuRmW_pWIm1:-Mt7tLA_1gsn-n4hj-_r:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-addresses/blob/47704229c871eadbcc886ce4091dbf81df9dcad2/README.md#L17)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

add something that mentions that it's per network, and that it is in the format of a json.
</blockquote></details>

Done.

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @bbrandtom)

___
*[README.md, line 20 at r2](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1#-Mt7tlia8pX7m2lELvD4:-Mt7tlia8pX7m2lELvD5:byt9zex) ([raw file](https://github.com/starkware-libs/starknet-addresses/blob/5ff7ae146116b7b45b04707bf6c1ec4fdea405cb/README.md#L20)):*
> ```Markdown
> 
> Under the bridged token addresses folders you will find Json files (one per network, currently only
> Goerli) containing the addresses of the tokens currently bridged to StarkNet. Each token has the
> ```

remove "currently only Goerli" as we will forget to update it.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

___
*[README.md, line 20 at r2](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1#-Mt7tlia8pX7m2lELvD4:-Mt7uedU01oz9An4OApD:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-addresses/blob/5ff7ae146116b7b45b04707bf6c1ec4fdea405cb/README.md#L20)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

remove "currently only Goerli" as we will forget to update it.
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-addresses/1#-:-Mt7uly44Y52Arin9FtX:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
